### ISSUE TITLE
Support for TLS connection / authentication

### ISSUE THREAD

**Issue by codeling** [Hsn723/postfix_exporter#142]
Thanks a lot for this very useful exporter!

I'd really love the option to use it directly via TLS without needing stunnel. Ideally it would also support basic_auth.

As examples, the [node_exporter](https://github.com/prometheus/node_exporter) and [apache_exporter](https://github.com/Lusitaniae/apache_exporter) do support this (via a `--web.config.file=` option), so I guess there is some support for this already somewhere, but I actually have no experience in developing prometheus exporters  myself...

**Comment by Hsn723** [comment]
Thank you for your suggestion.

This is indeed a useful feature to support so I'll consider it for inclusion. I can't guarantee any time line but I'll try to get it ready before the next release.

**Comment by Hsn723** [comment]
Support for `--web.config.file` as provided by the Prometheus exporter-toolkit has been added and included in the latest release: https://github.com/Hsn723/postfix_exporter/releases/tag/v0.7.0
